services:
  db:
    image: postgres:17.5-bookworm
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db-ui:
    image: dpage/pgadmin4:9.4.0
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "8080:80"
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json

configs:
  servers.json:
    content: |
      {
          "Servers": {
              "1": {
                  "Name": "Main DB",
                  "Group": "Servers",
                  "Host": "db",
                  "Port": 5432,
                  "MaintenanceDB": "postgres",
                  "Username": "tischmid",
                  "UseSSHTunnel": 0,
                  "TunnelPort": "22",
                  "TunnelAuthentication": 0,
                  "TunnelKeepAlive": 0,
                  "KerberosAuthentication": false,
                  "ConnectionParameters": {
                      "sslmode": "prefer",
                      "connect_timeout": 10,
                      "sslcert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
                      "sslkey": "<STORAGE_DIR>/.postgresql/postgresql.key"
                  },
                  "Tags": []
              }
          }
      }
